'use client'

import Head from "next/head";
import { createPost } from "~/server/db";
// import { db } from "~/server/db";
// import Link from "next/link";

const mockUrls = [
  "https://utfs.io/f/pvcc1agPKRfFuXvLQX831IU6mXlMiCp9q2PB54JZHkzrjhtA",
  "https://utfs.io/f/pvcc1agPKRfF1ZzlvWNctEOWMTyb5mDw2X3IjxaglP4VefQ7",
  "https://utfs.io/f/pvcc1agPKRfFYJIjRgygfD92kW6pVt7SGheiKCuHZNvc05ao",
  "https://utfs.io/f/pvcc1agPKRfFLOM9cWYXeabtsOKqHjuS4dDLUwMhlk2yE6x7",
  "https://utfs.io/f/pvcc1agPKRfFNdDveISPmBrbXQVet8Mp72GIh3WCcjv6di9a",
  "https://utfs.io/f/pvcc1agPKRfFAIKZH5WefjC32coJ0VnHKQlMWUE8a7Zi5zYs",
  "https://utfs.io/f/pvcc1agPKRfFC9e7uofvxps1cGZbiVRKQdUE9n8fNawol654",
  "https://utfs.io/f/pvcc1agPKRfFsk9hpLfyxjPzILREb6dQog1lTMSr9fZ5FUWV",
  "https://utfs.io/f/pvcc1agPKRfFY9YrG6ygfD92kW6pVt7SGheiKCuHZNvc05ao"
];

const mockImages = mockUrls.map((url, index) => ({
  id: index + 1,
  url
}))

console.log(mockImages);

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">  */}
        App in progress
        <button onClick={async () => {
          await createPost()
        }}>Create row</button>
        <div className="flex flex-wrap gap-10">
          {mockImages.map((image) => (
            <div key={image.id} className="w-1/5 p-4">
              <img src={image.url} alt="image" />
            </div>
          ))
          }
        </div>
        <div>another one</div>
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div> */}
      </main>
    </>
  );
}
